mysql:
  auth:
    rootPassword: "root"
  primary:
    service:
      type: NodePort
      nodePorts:
        mysql: 30006

logstash:
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: "resurse-app-elasticsearch"
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: ES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: resurse-app-elasticsearch
          key: elasticsearch-password
  service:
    type: NodePort
    ports:
      - name: logstash-tcp
        port: 5044
        targetPort: 5044
        protocol: TCP
        nodePort: 30544

elasticsearch:
  security:
    elasticPassword: "paassw0rd"

kibana:
  elasticsearch:
    security:
      auth:
        kibanaPassword: "paassw0rd"
        elasticsearchPasswordSecret: "resurse-app-elasticsearch"

keycloak:
  auth:
    adminPassword: "StrongPassword123!"
  postgresql:
    auth:
      password: "password123"
      postgresPassword: "password123"
