server:
  port: 8081

app:
  kafka:
    topic: testing-app-topic
  elk:
    elasticsearch-uri: http://elasticsearch:9200
    kibana-base-url: http://kibana:5601
    logstash-host: logstash
    logstash-port: 5044

logging:
  config: classpath:logback-spring.xml

spring:
  Kafka:
    bootstrap-servers: localhost:30001
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
