server:
  port: 8081

app:
  kafka:
    topic: testing-app-topic
  elk:
    elasticsearch-uri: https://resurse-app-elasticsearch:9200
    kibana-base-url: http://resurse-app-kibana:5601/kibana
    logstash-host: 127.0.0.1
    logstash-port: 30544

logging:
  config: classpath:logback-spring.xml

spring:
  Kafka:
    bootstrap-servers: localhost:30001
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
